import Head from "next/head";
import { Footer } from "../components/Footer";
import styles from "../styles/Home.module.css";
import { Links } from "../components/Links";

const About = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>About page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>About Pages</h1>
        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/about.js</code>
        </p>

        <Links />
      </main>

      <Footer />
    </div>
  );
};

export default About;
